### ISSUE TITLE
Как вы запускайте сам сервер?

### ISSUE THREAD

**Issue by ghost** [AvaCity/avacity-async#2]
Как вы запускайте сам сервер?

_Originally posted by @Noop1 in https://github.com/AvaCity/avacity-async/issues/1#issuecomment-683274697_

Сам сервер я запускаю через localhost, если вы имеете ввиду это

**Comment by Noop1** [comment]
Для ответа можно было и не создавать issues, какой командой вы запускайте сервер?

**Comment by ghost** [comment]
> Для ответа можно было и не создавать проблемы, какой командой вы запускайте сервер?

"python server.py" 
![image](https://user-images.githubusercontent.com/69242348/91635557-0ef51b80-ea02-11ea-855c-4f46c01dc6bf.png)

**Comment by Noop1** [comment]
Запускайте сервер с помощью python3 / python3.7 , но никак не с помощью просто python.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/69242348/91635621-9d699d00-ea02-11ea-9336-0f9732f6abc2.png)

**Comment by Noop1** [comment]
При установке пайтона на виндовс, вы должны были установить как минимум патч ( который предлагался в установке ).

**Comment by ghost** [comment]
Он предлагался, и устанавливался. Но видимо, не установился

**Comment by Noop1** [comment]
Попробуйте переустановить, не забудьте установить Redis.

**Comment by ghost** [comment]
Нужно именно Python3.7, или можно Python3.8.5?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/69242348/91636263-e53ef300-ea07-11ea-9457-d02a0e392a2f.png)

**Comment by Noop1** [comment]
Желательно использовать python3.7 и лучше запускать на виртуальной машине

**Comment by ams259** [comment]
Неделю назад где-то, я пробовал запустить на виртуальной машине(Через ОС Ubuntu) сервер. Он заработал, но там была другая ошибка, я только потом разобрался, как ее устранить. Но сейчас там проблема такая же, как и на Windows.

**Comment by ams259** [comment]
![image](https://user-images.githubusercontent.com/69242348/91643708-3f5aab00-ea3e-11ea-8034-e6020afdd0da.png)
За что отвечают эти строки?

**Comment by ams259** [comment]
Traceback (most recent call last):
  File "server.py", line 477, in <module>
    server = Server()
  File "server.py", line 43, in __init__
    self.modules[class_.prefix] = class_(self)
  File "E:\AvaMine\modules\avatar.py", line 16, in __init__
    self.clothes_list = server.parser.parse_clothes()
  File "E:\AvaMine\xml_parser.py", line 17, in parse_clothes
    root = doc.getroot()
NameError: name 'doc' is not defined

На данный момент ршибка такая.

**Comment by ghost** [comment]
> Желательно использовать python3.7 и лучше запускать на данную машину

Теперь в консоли пишет, что сервер готов принимать подключения. Но мервер до сих пор не может загрузиться, и после 30 секунд загрузки появляется черный экран... 
![image](https://user-images.githubusercontent.com/69242348/91716949-3cc09880-eb99-11ea-8990-b18050698ea0.png)
